export type AffiliateNetwork = 'direct' | 'awin' | 'cj' | 'shareasale' | 'refersion';
export type CoaAccess = 'public' | 'qr-code' | 'request' | 'none';
export type CatalogBreadth = 'narrow' | 'medium' | 'broad' | 'very-broad';
export type ShippingSpeed = 'same-day' | '24h' | '2-3d' | 'variable';
export type VendorFormat = 'vials' | 'blends' | 'capsules' | 'sprays' | 'topicals';
export type Payment = 'cards' | 'crypto' | 'ach' | 'zelle' | 'paypal';
export type VendorSource = 'peptidescores' | 'peptidesupermarket' | 'manual';

export interface Vendor {
  slug: string;
  name: string;
  logo: string | null;
  website: string | null;
  affiliateUrl: string | null;
  affiliateNetwork: AffiliateNetwork | null;
  couponCode: string | null;
  couponDiscount: string | null;
  couponStackable: boolean;
  scoreGlobal: number;
  scorePurity: number;
  scoreTesting: number;
  scoreTransparency: number;
  scoreShipping: number;
  scoreValue: number;
  scoreService: number;
  badges: string[];
  testingLabs: string[];
  testingPanel: string;
  coaAccess: CoaAccess;
  coaArchive: boolean;
  conformityTesting: string;
  formats: VendorFormat[];
  catalogBreadth: CatalogBreadth;
  rarePeptides: boolean;
  customSynthesis: boolean;
  basedIn: string;
  shipsTo: string[];
  shippingSpeed: ShippingSpeed;
  freeShippingThreshold: number | null;
  domesticOnly: boolean;
  payments: Payment[];
  yearsOperating: number | null;
  communityFav: boolean;
  risingStar: boolean;
  newEntry: boolean;
  source: VendorSource;
  lastVerified: string;
  notesFr: string;
  sourceUrl: string | null;
}
